# Generated by Django 2.2.16 on 2020-09-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('phone_num', models.CharField(default='000-000-000', max_length=12, verbose_name='Phone Number')),
                ('ceo_name', models.CharField(max_length=50, verbose_name='CEO')),
                ('num_employees', models.IntegerField(default=0, verbose_name='Number of Employees')),
                ('maintenance_schedule', models.CharField(max_length=100, verbose_name='maintenance schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Soft_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_crew_title', models.CharField(max_length=200)),
                ('cleaning_crew_title', models.CharField(max_length=200)),
                ('landscaping_crew_title', models.CharField(max_length=200)),
                ('caterers', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Safety_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_schedule', models.DurationField(verbose_name='training schedule')),
                ('audit_schedule', models.DurationField(verbose_name='audit schedule')),
                ('saftety_meetings', models.DateTimeField(verbose_name='meeting schedule')),
                ('safety_coordinator', models.CharField(max_length=150)),
                ('job_safety_analysis', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leasee_name', models.CharField(max_length=150)),
                ('rate', models.FloatField(default=0.0)),
                ('date', models.DateField(verbose_name='Start Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Hard_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electric_provider', models.CharField(max_length=200)),
                ('plumbing_provider', models.CharField(max_length=200)),
                ('hvac_provider', models.CharField(max_length=200)),
                ('mechanical_provider', models.CharField(max_length=200)),
                ('fire_safety_provider', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
